"""Re-sort pokemon table

Revision ID: 10c52b154de8
Revises: 2eccecfe7dd2
Create Date: 2025-07-13 13:47:59.562078

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10c52b154de8"
down_revision = "2eccecfe7dd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("generation", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("type1", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("type2", sa.String(length=10), nullable=True))
        batch_op.drop_column("hiddenAbility")
        batch_op.drop_column("smogon")
        batch_op.drop_column("abilities")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("abilities", sa.VARCHAR(length=30), nullable=True),
        )
        batch_op.add_column(sa.Column("smogon", sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column("hiddenAbility", sa.BOOLEAN(), nullable=True))
        batch_op.drop_column("type2")
        batch_op.drop_column("type1")
        batch_op.drop_column("generation")

    # ### end Alembic commands ###
