"""Initial user, pokemon and userpokemon models

Revision ID: 2eccecfe7dd2
Revises:
Create Date: 2025-07-13 13:16:48.835695

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2eccecfe7dd2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("dexNum", sa.Integer(), nullable=True),
        sa.Column("formId", sa.String(length=10), nullable=True),
        sa.Column("smogon", sa.String(length=30), nullable=True),
        sa.Column("isFemale", sa.Boolean(), nullable=True),
        sa.Column("hiddenAbility", sa.Boolean(), nullable=True),
        sa.Column("abilities", sa.String(length=30), nullable=True),
        sa.Column("sprite", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("ball_fast", sa.Boolean(), nullable=True),
        sa.Column("ball_lure", sa.Boolean(), nullable=True),
        sa.Column("ball_level", sa.Boolean(), nullable=True),
        sa.Column("ball_heavy", sa.Boolean(), nullable=True),
        sa.Column("ball_love", sa.Boolean(), nullable=True),
        sa.Column("ball_moon", sa.Boolean(), nullable=True),
        sa.Column("ball_dream", sa.Boolean(), nullable=True),
        sa.Column("ball_beast", sa.Boolean(), nullable=True),
        sa.Column("ball_safari", sa.Boolean(), nullable=True),
        sa.Column("ball_sport", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pokemon_id"],
            ["pokemon.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_pokemon")
    op.drop_table("pokemon")
    # ### end Alembic commands ###
