"""add legendary

Revision ID: 5484c53bfb41
Revises: 5543adceba6a
Create Date: 2025-09-28 20:42:50.048683

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5484c53bfb41"
down_revision = "5543adceba6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_legendary", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.drop_column("is_legendary")

    # ### end Alembic commands ###
