"""condense ball names

Revision ID: 5768e560d778
Revises: 7bd4d0a53b3a
Create Date: 2025-07-13 14:44:13.908704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5768e560d778'
down_revision = '7bd4d0a53b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fast', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lure', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('heavy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('love', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('moon', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dream', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('beast', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('safari', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sport', sa.Boolean(), nullable=True))
        batch_op.drop_column('ball_beast')
        batch_op.drop_column('ball_moon')
        batch_op.drop_column('ball_level')
        batch_op.drop_column('ball_dream')
        batch_op.drop_column('ball_heavy')
        batch_op.drop_column('ball_love')
        batch_op.drop_column('ball_fast')
        batch_op.drop_column('ball_safari')
        batch_op.drop_column('ball_sport')
        batch_op.drop_column('ball_lure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ball_lure', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_sport', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_safari', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_fast', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_love', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_heavy', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_dream', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_level', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_moon', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ball_beast', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('sport')
        batch_op.drop_column('safari')
        batch_op.drop_column('beast')
        batch_op.drop_column('dream')
        batch_op.drop_column('moon')
        batch_op.drop_column('love')
        batch_op.drop_column('heavy')
        batch_op.drop_column('level')
        batch_op.drop_column('lure')
        batch_op.drop_column('fast')

    # ### end Alembic commands ###
