"""Pokemon table capitalisation

Revision ID: 7bd4d0a53b3a
Revises: 10c52b154de8
Create Date: 2025-07-13 14:00:00.489636

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bd4d0a53b3a"
down_revision = "10c52b154de8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dex_num", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("form_id", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("is_female", sa.Boolean(), nullable=True))
        batch_op.drop_column("dexNum")
        batch_op.drop_column("formId")
        batch_op.drop_column("isFemale")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("isFemale", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("formId", sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column("dexNum", sa.INTEGER(), nullable=True))
        batch_op.drop_column("is_female")
        batch_op.drop_column("form_id")
        batch_op.drop_column("dex_num")

    # ### end Alembic commands ###
