"""add custom categories

Revision ID: a8e4add3afee
Revises: 5768e560d778
Create Date: 2025-07-19 16:14:19.899179

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8e4add3afee"
down_revision = "5768e560d778"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "custom_category_pokemon",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("user_pokemon_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["custom_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_pokemon_id"],
            ["user_pokemon.id"],
        ),
        sa.PrimaryKeyConstraint("category_id", "user_pokemon_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_category_pokemon")
    op.drop_table("custom_category")
    # ### end Alembic commands ###
