"""add is_start is_legendary

Revision ID: ce5c9ea3e84c
Revises: a8e4add3afee
Create Date: 2025-07-19 17:02:29.286825

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce5c9ea3e84c"
down_revision = "a8e4add3afee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_starter", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("is_legendary", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.drop_column("is_legendary")
        batch_op.drop_column("is_starter")

    # ### end Alembic commands ###
